### ISSUE TITLE
duplicated fields

### ISSUE THREAD

**Issue by serazoli** [samber/slog-graylog#3]
Hi
When  i use the provided example than in the graylog whole json appear in the message filed. I think it would be nice if gelf-writer could unpack the existing fields and use them. The question is that how you use your lib to prevent duplication?
Thaks
![Screenshot_20240226_115644](https://github.com/samber/slog-graylog/assets/11732/5a6391a5-3895-4178-91d6-1766fe815090)

**Comment by samber** [comment]
Thanks for the report @serazoli 

I made a fix in v2.4.0. It should match the gelf format now!

**Comment by serazoli** [comment]
Thank you
